# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Which Stream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Which Stream
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

  target 'Which StreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Which StreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
